### ISSUE TITLE
Style pin Popup

### ISSUE THREAD

**Issue by Plumtree3D** [WildCodeSchool/2209-wns-lovelace-city-guide#62]
- [ ] Displays image gallery
- [ ] Accéder à la page du pin
- [ ] Ajouter une image
- [ ] modifier / supprimer le pin si admin ou propriétaire

```[tasklist]
### Tasks
```
